services:
  nginx-proxy:
    build: nginx
    restart: always
    depends_on:
      - flask-app
    environment: 
      - APP_ADDR=flask-app:8000
      - SERVER_NAME=${SERVER_NAME}
      - CONF_TEMPLATE=${CONF_TEMPLATE}
    ports:
      - 80:80
      - 443:443
    volumes:  
      - ${CERTBOT_PATH}/www:/var/www/certbot/:ro
      - ${CERTBOT_PATH}/config/:/etc/nginx/ssl/:ro
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
    
  flask-app:
    build: .
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 600 -b 0.0.0.0:8000 main:app
